#line 2 "lex.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
//nclude <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
static yyconst short int yy_acclist[247] =
    {   0,
       90,   88,   89,   86,   88,   89,   87,   89,   61,   88,
       89,    1,   88,   89,   72,   88,   89,   88,   89,   85,
       88,   89,   85,   88,   89,   52,   88,   89,   39,   83,
       88,   89,   40,   83,   88,   89,   41,   83,   88,   89,
       83,   88,   89,   83,   88,   89,   83,   88,   89,   83,
       88,   89,   45,   83,   88,   89,   46,   83,   88,   89,
       83,   88,   89,   83,   88,   89,   83,   88,   89,   83,
       88,   89,   42,   83,   88,   89,   43,   83,   88,   89,
       44,   83,   88,   89,   58,   89,   60,   89,   59,   89,
       54,   89,   53,   89,   54,   55,   89,   71,   89,   70,

       89,   62,   71,   89,   71,   89,   82,   89,   81,   89,
       73,   82,   89,   82,   89,   56,   52,   85,   83,   83,
       83,   83,   83,    3,   83,   83,   83,    4,   83,   83,
       47,   83,   83,   83,   83,   83,   83,   83,   83,   38,
       83,   83,   83,   83,   83,   83,   83,   37,   83,   83,
       83,   58,   57,   54,   63,   64,   65,   66,   67,   68,
       69,   74,   75,   76,   77,   78,   79,   80,   84,    7,
       83,   28,   83,   14,   83,   18,   83,   15,   83,   11,
       83,   12,   83,    2,   83,   36,   83,   35,   83,   34,
       83,   25,   83,   20,   83,   21,   83,   22,   83,   24,

       83,   26,   83,   23,   83,   27,   83,   32,   83,   33,
       83,   31,   83,   30,   83,   13,   83,   10,   83,    9,
       83,    5,   83,   83,   83,   48,   83,   83,    6,   83,
       19,   83,   17,   83,    8,   83,   29,   83,   16,   83,
       49,   83,   51,   83,   50,   83
    } ;

static yyconst short int yy_accept[144] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    7,    9,   12,   15,   18,   20,   23,
       26,   29,   33,   37,   41,   44,   47,   50,   53,   57,
       61,   64,   67,   70,   73,   77,   81,   85,   87,   89,
       91,   93,   95,   98,  100,  102,  105,  107,  109,  111,
      114,  116,  117,  118,  118,  119,  120,  121,  122,  123,
      124,  126,  127,  128,  130,  131,  133,  134,  135,  136,
      137,  138,  139,  140,  142,  143,  144,  145,  146,  147,
      148,  150,  151,  152,  153,  154,  155,  156,  157,  158,
      159,  160,  161,  162,  163,  164,  165,  166,  167,  168,

      169,  170,  172,  174,  176,  178,  180,  182,  184,  186,
      188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
      208,  210,  212,  214,  216,  218,  220,  222,  224,  225,
      226,  228,  229,  231,  233,  235,  237,  239,  241,  243,
      245,  247,  247
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    6,    5,
        5,    7,    5,    5,    5,    1,    8,    9,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    5,   11,    1,
        5,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
        5,   12,    5,    1,    1,    1,   13,   14,   15,   16,

       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    4,    4,
        1,    1,    4,    4,    4,    4,    4,    4,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst short int yy_base[151] =
    {   0,
        0,    0,   36,   37,   38,   39,   45,   47,   49,   50,
      135,  212,  212,  212,  212,  212,  212,   56,   98,   56,
      212,   42,  106,    0,   46,   40,    0,   95,   52,   97,
       44,   97,   67,   69,   99,    0,    0,    0,  212,  116,
        0,  212,    0,  212,  212,  212,   99,  212,  212,  212,
      126,  212,  212,    0,   65,    0,   56,  107,   92,   91,
        0,   86,   98,    0,   85,    0,   64,  146,   64,   86,
       99,   77,   95,    0,   94,   95,   80,   76,   74,   75,
        0,   73,   74,    0,  212,    0,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   56,
        0,   34,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  212,  179,  184,  189,  194,  196,  201,  206,   41
    } ;

static yyconst short int yy_def[151] =
    {   0,
      142,    1,  143,  143,  144,  144,  145,  145,  146,  146,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  148,  142,  142,
      149,  142,  149,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  150,  142,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  148,  142,  149,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,

      150,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,    0,  142,  142,  142,  142,  142,  142,  142,  142
    } ;

static yyconst short int yy_nxt[251] =
    {   0,
       12,   13,   14,   15,   16,   17,   16,   18,   19,   20,
       21,   12,   22,   23,   24,   25,   26,   27,   27,   28,
       29,   30,   27,   27,   31,   27,   32,   33,   27,   27,
       34,   27,   27,   27,   27,   35,   36,   37,   39,   39,
       42,   42,   40,   40,  101,   43,   43,   45,   46,   45,
       46,   49,   49,  141,   50,   50,   47,   57,   47,   61,
       51,   51,   52,   53,   55,   55,   62,   58,   65,   68,
       71,  102,   59,   55,   55,   66,   72,   69,  140,   63,
       64,   74,  121,   75,  110,   79,  136,   76,   80,  111,
      139,  103,  112,   77,  122,  123,   81,  126,  134,   78,

      127,   82,   87,  138,  135,  133,  132,  131,  137,  130,
      129,   88,   89,  128,  125,  124,   90,  109,  108,  107,
      106,  105,  104,   85,   91,   83,   73,   70,   92,   67,
       93,   94,   60,   54,  142,  142,  142,  142,   95,   96,
      142,  142,  142,   97,  142,  142,  142,  142,  142,  142,
      142,   98,  142,  142,  142,   99,  142,  100,  113,  114,
      115,  142,  116,  142,  117,  142,  142,  142,  142,  118,
      142,  119,  142,  142,  142,  142,  142,  142,  120,   38,
       38,   38,   38,   38,   41,   41,   41,   41,   41,   44,
       44,   44,   44,   44,   48,   48,   48,   48,   48,   56,

       56,   84,  142,  142,   84,   84,   86,  142,   86,   86,
       86,   11,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142
    } ;

static yyconst short int yy_chk[251] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,    3,    4,  150,    5,    6,    7,    7,    8,
        8,    9,   10,  132,    9,   10,    7,   22,    8,   25,
        9,   10,   18,   18,   20,   20,   25,   22,   26,   29,
       31,   57,   22,   55,   55,   26,   31,   29,  130,   25,
       25,   33,   69,   33,   67,   34,   82,   33,   34,   67,
      129,   57,   67,   33,   69,   69,   34,   72,   80,   33,

       72,   34,   47,   83,   80,   79,   78,   77,   82,   76,
       75,   47,   47,   73,   71,   70,   47,   65,   63,   62,
       60,   59,   58,   40,   47,   35,   32,   30,   47,   28,
       47,   51,   23,   19,   11,    0,    0,    0,   51,   51,
        0,    0,    0,   51,    0,    0,    0,    0,    0,    0,
        0,   51,    0,    0,    0,   51,    0,   51,   68,   68,
       68,    0,   68,    0,   68,    0,    0,    0,    0,   68,
        0,   68,    0,    0,    0,    0,    0,    0,   68,  143,
      143,  143,  143,  143,  144,  144,  144,  144,  144,  145,
      145,  145,  145,  145,  146,  146,  146,  146,  146,  147,

      147,  148,    0,    0,  148,  148,  149,    0,  149,  149,
      149,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  142,  142,  142,  142,  142,  142
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "dcpu16.flex"
#define INITIAL 0
#define YY_STACK_USED 1
#define YY_NEVER_INTERACTIVE 1
#line 3 "dcpu16.flex"
	#include "dcpu16.h"
	#include "parser.h"
	#include <malloc.h>
	#include <io.h>       // isatty
	#include <assert.h>	

	//#define token(x) (x)
	#define token(x) ((x))
	long char_lit_val = -1;
	int str_or_char = 0;
#define comment_block 1

#define comment_line 2

#define strlit 3

#define chrlit 4

#line 524 "lex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 25 "dcpu16.flex"

#line 673 "lex.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 143 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 212 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 26 "dcpu16.flex"
{ return token(yytext[0]); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "dcpu16.flex"
{ return token(EQU); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "dcpu16.flex"
{ return token(BYTE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "dcpu16.flex"
{ return token(WORD); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "dcpu16.flex"
{ return token(ORGIN); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "dcpu16.flex"
{  return token(SET); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "dcpu16.flex"
{  return token(ADD); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "dcpu16.flex"
{  return token(SUB); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "dcpu16.flex"
{  return token(MUL); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "dcpu16.flex"
{  return token(MUI); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "dcpu16.flex"
{  return token(DIV); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "dcpu16.flex"
{  return token(DVI); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "dcpu16.flex"
{  return token(MOD); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "dcpu16.flex"
{  return token(AND); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "dcpu16.flex"
{  return token(BOR); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "dcpu16.flex"
{  return token(XOR); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "dcpu16.flex"
{  return token(SHR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "dcpu16.flex"
{  return token(ASR); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "dcpu16.flex"
{  return token(SHL); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "dcpu16.flex"
{  return token(IFB); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "dcpu16.flex"
{  return token(IFC); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "dcpu16.flex"
{  return token(IFE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "dcpu16.flex"
{  return token(IFN); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "dcpu16.flex"
{  return token(IFG); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "dcpu16.flex"
{  return token(IFA); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "dcpu16.flex"
{  return token(IFL); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "dcpu16.flex"
{  return token(IFU); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "dcpu16.flex"
{  return token(ADX); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "dcpu16.flex"
{  return token(SUX); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "dcpu16.flex"
{  return token(JSR); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "dcpu16.flex"
{  return token(INT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "dcpu16.flex"
{  return token(ING); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "dcpu16.flex"
{  return token(INS); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "dcpu16.flex"
{  return token(HWQ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "dcpu16.flex"
{  return token(HWN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "dcpu16.flex"
{  return token(HWI); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 66 "dcpu16.flex"
{  return token(REG_SP); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 67 "dcpu16.flex"
{  return token(REG_PC); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 68 "dcpu16.flex"
{  return token(REG_A); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "dcpu16.flex"
{  return token(REG_B); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "dcpu16.flex"
{  return token(REG_C); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 71 "dcpu16.flex"
{  return token(REG_X); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 72 "dcpu16.flex"
{  return token(REG_Y); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "dcpu16.flex"
{  return token(REG_Z); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 74 "dcpu16.flex"
{  return token(REG_I); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 75 "dcpu16.flex"
{  return token(REG_J); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "dcpu16.flex"
{  return token(REG_EX); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "dcpu16.flex"
{  return token(POP);  }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 79 "dcpu16.flex"
{  return token(PEEK); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 80 "dcpu16.flex"
{  return token(PUSH); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 81 "dcpu16.flex"
{  return token(PICK); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "dcpu16.flex"
{  BEGIN(comment_line); }
	YY_BREAK

case 53:
YY_RULE_SETUP
#line 85 "dcpu16.flex"
{   BEGIN(INITIAL);  return token(EOL); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "dcpu16.flex"
{  }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 87 "dcpu16.flex"
{  }
	YY_BREAK

case 56:
YY_RULE_SETUP
#line 90 "dcpu16.flex"
{  BEGIN(comment_block); }
	YY_BREAK

case 57:
YY_RULE_SETUP
#line 92 "dcpu16.flex"
{  BEGIN(INITIAL); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "dcpu16.flex"
{  }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "dcpu16.flex"
{  }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "dcpu16.flex"
{  }
	YY_BREAK

case 61:
YY_RULE_SETUP
#line 97 "dcpu16.flex"
{ vec_init(); BEGIN(strlit); }
	YY_BREAK

case 62:
YY_RULE_SETUP
#line 99 "dcpu16.flex"
{ BEGIN(INITIAL);
						yylval._string = vec_strdup();
						printf("TEST: %s\n",yylval._string); 
						return token(STRING);  
					  }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "dcpu16.flex"
{ vec_putc('"');     }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "dcpu16.flex"
{ vec_putc('\a');    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "dcpu16.flex"
{ vec_putc('\b');    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "dcpu16.flex"
{ vec_putc('\f');    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "dcpu16.flex"
{ vec_putc('\n');    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "dcpu16.flex"
{ vec_putc('\r');    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "dcpu16.flex"
{ vec_putc('\t');    }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "dcpu16.flex"
{ yyerror("End of line before end of string"); fatal_error(1); return 0;   }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "dcpu16.flex"
{ vec_putc(*yytext);  }
	YY_BREAK

case 72:
YY_RULE_SETUP
#line 114 "dcpu16.flex"
{ yylval._num = 0; BEGIN(chrlit); }
	YY_BREAK

case 73:
YY_RULE_SETUP
#line 116 "dcpu16.flex"
{ BEGIN(INITIAL); printf("TEST: %c\n",yylval._num); return token(NUMBER);  }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 117 "dcpu16.flex"
{ yylval._num = '\'';    }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 118 "dcpu16.flex"
{ yylval._num = '\a';    }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 119 "dcpu16.flex"
{ yylval._num = '\b';    }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 120 "dcpu16.flex"
{ yylval._num = '\f';    }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 121 "dcpu16.flex"
{ yylval._num = '\n';    }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 122 "dcpu16.flex"
{ yylval._num = '\r';    }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 123 "dcpu16.flex"
{ yylval._num = '\t';    }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 124 "dcpu16.flex"
{ yyerror("End of line before end of char"); fatal_error(1); return 0;   }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 125 "dcpu16.flex"
{ yylval._num = *yytext;  }
	YY_BREAK

case 83:
YY_RULE_SETUP
#line 128 "dcpu16.flex"
{	 
							yylval._ident = tagstr(yytext);
							return token(IDENT);  
						}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 132 "dcpu16.flex"
{  sscanf(yytext, "%x", &yylval._num); return token(NUMBER); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 133 "dcpu16.flex"
{  yylval._num = atoi(yytext); return token(NUMBER); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 135 "dcpu16.flex"
{  } /* ignore whitespace */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 136 "dcpu16.flex"
{ return token(EOL); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment_block):
case YY_STATE_EOF(comment_line):
case YY_STATE_EOF(strlit):
case YY_STATE_EOF(chrlit):
#line 137 "dcpu16.flex"
{ return EOFILE;  }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 139 "dcpu16.flex"
{ yyerror("Invalid Token %s", yytext); return 0; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 140 "dcpu16.flex"
ECHO;
	YY_BREAK
#line 1232 "lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 143 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 143 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 142);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 140 "dcpu16.flex"


